apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-backend-app
  name: k8s-backend-svc
  namespace: project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    # nodePort: 32309
  selector:
    app: k8s-backend-app
  # type: NodePort
