apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/c/Users/ibadin/OneDrive/Desktop/K8s-project/k8s-project-three-tier-application/mnt/data/postgres"